server.port=8012
management.server.port=8012

#######################################
#	Database
#######################################
spring.data.mongodb.uri=mongodb://mongo:27017
spring.data.mongodb.database=FSE_GTW

#########################
# LOGGER CONFIGURATION  #
#########################
log.output.format=console

kafka.bootstrap-servers=kafka:29092
spring.sleuth.messaging.kafka.enabled=false
kafka.properties.security.protocol=PLAINTEXT
kafka.properties.sasl.mechanism=PLAINTEXT
kafka.properties.sasl.jaas.config=PLAINTEXT
kafka.log.base-topic=MDS-SA-0004_FU_001_LOG
kafka.properties.ssl.truststore.location=
kafka.properties.ssl.truststore.password=
kafka.enablessl=false
kafka.oauth.tenantId=
kafka.oauth.appId=
kafka.oauth.pfxPathName=
kafka.oauth.pwd=
###########################
ms.url.gtw-config=http://it-fse-gtw-config:8018

########OPENTELEMETRY################################
otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none

otel.propagators=tracecontext,baggage